import Head from "next/head";
import Image from "next/image";
import { request } from "@octokit/request";
import styles from "../styles/Home.module.css";

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const result = await request("GET /repos/{owner}/{repo}/stats/contributors", {
    headers: {
      authorization: "token GITHUB_AUTH_TOKEN_WITH_ORG_READ_PERMISSION",
    },
    owner: "chatwoot",
    repo: "chatwoot",
  });

  // Pass data to the page via props
  return {
    props: { contributors: result.data.sort((a, b) => b.total - a.total) },
  };
}

export default function Home({ contributors }) {
  return (
    <div className="bg-madiwala-200">
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header></header>
        <section className="flex flex-col items-center justify-center p-24 text-center">
          <h1 className="text-4xl text-madiwala-900 font-bold mb-4">
            We thank all our contributors.
          </h1>
          <p className="text-lg mb-8 text-madiwala-800 max-w-lg ml-auto mr-auto">
            Chatwoot would not have been what it is today without the help of
            our amazing contributors.
          </p>
          <div>
            <button className="px-4 py-2 border-2 text-madiwala-700 font-semibold border-madiwala-600 bg-varakala-100 drop-shadow-flat mr-4">
              🐙 See us on gitHub
            </button>
            <button className="px-4 py-2 border-2 text-chennai-700 font-semibold border-madiwala-600 bg-varakala-100 drop-shadow-flat mr-4">
              📚 How to contribute
            </button>
            <button className="px-4 py-2 border-2 text-varakala-700 font-semibold border-madiwala-600 bg-varakala-100 drop-shadow-flat">
              ❤️ Sponsor us
            </button>
          </div>
        </section>
        <section className="flex  items-center justify-center px-24 py-8">
          <h3 className="text-3xl font-bold text-chennai-800">
            Showing all <strong>{contributors.length} contributors 🌈</strong>
          </h3>
        </section>

        <section className="flex  items-center justify-center px-24 py-8">
          <table className="table-auto  min-w-3xl bg-chennai-100  border-2 text-varakala-700 font-semibold border-madiwala-600 drop-shadow-flat">
            <thead>
              <tr>
                <th className="p-4 pr-8 text-left text-lg font-bold text-chennai-800">
                  Contributor
                </th>
                <th className="p-4 pr-12 text-left text-lg font-bold text-chennai-800">
                  First commit on
                </th>
                <th className="p-4 pr-12 text-left text-lg font-bold text-chennai-800">
                  Total commits
                </th>
              </tr>
            </thead>
            <tbody>
              {contributors.map((contributor) => {
                const firstWeekOfCommit = contributor.weeks.find(
                  (week) => week.c !== 0
                );
                const date = new Date(
                  firstWeekOfCommit.w * 1000
                ).toLocaleDateString("en-US");

                return (
                  <tr key={contributor.author.id}>
                    <td className="px-4 py-2 text-left">
                      <a
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center"
                        href={contributor.author.html_url}
                      >
                        <div className="flex items-center">
                          <Image
                            alt={`Profile picture of ${contributor.author.login}`}
                            src={contributor.author.avatar_url}
                            width="20"
                            height="20"
                            className="rounded-full"
                          />
                        </div>
                        <span className="pl-2 underline text-ulsoor-700">
                          {contributor.author.login}
                        </span>
                      </a>
                    </td>
                    <td className="px-4 py-2 text-left text-ulsoor-700  font-semibold">
                      {date}
                    </td>
                    <td className="px-4 py-2 text-left text-ulsoor-700  font-semibold">
                      {contributor.total}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel and Replit
        </a>
      </footer>
    </div>
  );
}
